### ISSUE TITLE
Validate your Project Idea

### ISSUE THREAD

**Issue by santiagobasulto** [rmotr-career-services/career-services-jwinf843#1]
Now that you've chosen your project idea, it's time to make sure it's feasible before you commit to it.

Things to check:

- If you are using API's, try each one out and make sure the information you are getting is what you expect. Sometimes you have to request an API key to get access.
- If you are using third party libraries, check out the documentation/try them out and make sure they work as you expect.
- Does your project idea have any legal considerations?
- Do you think you can realistically develop your project in two weeks?

**Deliverable**: Write the research you did to validate your project idea and your findings from it below in a comment and then close the issue.

`RMOTR: DD#3`

**Comment by jwinf843** [comment]
Ideas approved by Jason and Santa
