### ISSUE TITLE
Clean up your Github profile

### ISSUE THREAD

**Issue by santiagobasulto** [rmotr-career-services/career-services-jwinf843#18]
Make it look good:
* Make sure you have a good picture
* Pin 2 or 3 repos to your profile

A good read on github profiles:
https://www.quora.com/How-do-I-have-a-stellar-GitHub-profile

Polish your repos according to this:
https://gist.github.com/ndelage/7583138

**Deliverable:** Once you're done. Post your Github public URL in this issue and close it for review.

`RMOTR: PB#3`

**Comment by jwinf843** [comment]
https://github.com/jwinf843

**Comment by jasonmeeks** [comment]
Looks good! I'm surprised you didn't pin any rmotr projects! Make sure you pin your demo day repos.

**Comment by jasonmeeks** [comment]
Oh wait. You still need a bio!
