### ISSUE TITLE
Clean up your LinkedIn profile

### ISSUE THREAD

**Issue by santiagobasulto** [rmotr-career-services/career-services-jwinf843#19]
Key points:
- Good portfolio picture
- Detailed employment information (sell yourself on how you made a difference at your workplaces)
- References
- Connections with people in relevant fields, old co-workers
- Make sure you include your other social profiles and links
- Validate that your profile is publicly visible
- Include RMOTR's course in your Education section

Follow this guide for advice:
https://www.themuse.com/advice/the-31-best-linkedin-profile-tips-for-job-seekers

**Deliverable:** Once you're done. Post your LinkedIn public URL in this issue and close it for review.

`RMOTR: PB#2`

**Comment by jwinf843** [comment]
https://www.linkedin.com/in/jordan-winfrey-108ba592/

I wasn't able to find the place to get a personalized URL for my LinkedIn account

**Comment by jwinf843** [comment]
www.linkedin.com/in/jwinfery

Richard walked me through changing to a personalized URL

**Comment by jasonmeeks** [comment]
Good job with this! Only thing I would change is in your summary from "Skilled Python" to "Skilled in Python" or something
