### ISSUE TITLE
Create working project prototype

### ISSUE THREAD

**Issue by santiagobasulto** [rmotr-career-services/career-services-jwinf843#5]
After defining your project and your scope, you have two weeks to create a working prototype.

You'll need to meet two goals:

**Comment by jwinf843** [comment]
naoko-and-jordan.herokuapp.com

femicide-project-rmotr.herokuapp.com

color-poster-project.herokuapp.com

I have working prototypes of each project available now, but the prototype for the color poster project isn't pushed to Heroku yet.
