### ISSUE TITLE
Pick a project idea

### ISSUE THREAD

**Issue by santiagobasulto** [rmotr-career-services/career-services-jwinf843#7]
It is recommended that you come up with at least 3 ideas for your project and then choose the one you like the best and seems the most technically feasible.

**Deliverable**: Once you have selected your project idea, write the idea and why you chose it in this issue and close it for review.

`RMOTR: DD#2`

**Comment by jwinf843** [comment]
Worked with both Richard and Berenice to bring their project ideas to fruition. My own ideas were shot down by Santa because games are hard and my dreams have been crushed
