### ISSUE TITLE
Review Demo Day Specs and Form Teams

### ISSUE THREAD

**Issue by santiagobasulto** [rmotr-career-services/career-services-jwinf843#8]
Read the spec to make sure you are clear on the project requirements:
https://docs.google.com/document/d/1K3uZBOLgJ-RPLzO0QCKStzdfbNAtagLSodamaV8-wlk/edit?usp=sharing

**Deliverable**: Decide if you will work alone or as a team for Demo Day. After you have read over and discussed the spec with your group, post your group members as a comment and close the issue.

`RMOTR: DD#1`

**Comment by jwinf843** [comment]
Formed a team with Berenice covering femicide information and another team with Richard working on a django app that helps select posters to match specific colors.
